[package]
name = "aurorac"
version = "0.1.0"
edition = "2021"

[features]
debug = []

[dependencies]
regex = "1.7.3"
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = ["llvm14-0"] }
cc = "1.0.79"
